name: Build & Deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git pull
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          command_timeout: 200m
          script: |
            cd ${{secrets.APP_DIR}}
            git fetch
            git reset origin/master --hard
      - name: npm install
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          command_timeout: 200m
          script: |
            cd ${{secrets.APP_DIR}}
            docker-compose -f docker-compose-prd.yml run --rm node npm install
      - name: Build react app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          command_timeout: 200m
          script: |
            cd ${{secrets.APP_DIR}}
            docker-compose -f docker-compose-prd.yml build
      - name: Deploy react app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd ${{secrets.APP_DIR}}
            docker service update app-maliin_app
