name: Build & Deploy
on:
  push:
    branches: [ develop ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git pull
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          command_timeout: 200m
          script: |
            cd ~/app/app-maliin
            git fetch
            git reset origin/master --hard
            docker-compose -f docker-compose-prd.yml down -v
            docker networks prune --force
            docker system prune -a --force
            docker-compose -f docker-compose-prd.yml build node
      - name: npm install
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          command_timeout: 200m
          script: |
            cd ~/app/app-maliin
            docker-compose -f docker-compose-prd.yml run --rm node npm install
      - name: Build react app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          command_timeout: 200m
          script: |
            cd ~/app/app-maliin
            docker-compose -f docker-compose-prd.yml build
      - name: Deploy react app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd ~/app/app-maliin
            docker stack deploy -c docker-compose-prd.yml app-maliin
